# Copyright FUJITSU LIMITED 2015-2017.

- hosts: all
  become: yes
  vars_files:
    - ./group_vars/common.yml
  tasks:
    - include: ./tasks/common/check_base_url.yml
    - include: ./common.yml

- hosts: tag_ServerType_bastion
  become: yes
  vars_files:
    - ./group_vars/bastion.yml
  tasks:
    - include: ./tasks/common/check_base_url.yml
    - include: ./bastion.yml
  handlers:
    - include: ./handlers/common/restart_iptables.yml
  tags:
    - bastion_pre

- hosts: tag_ServerType_es
  become: yes
  vars_files:
    - ./group_vars/es.yml
  tasks:
    - include: ./es.yml
  handlers:
    - include: ./handlers/common/restart_iptables.yml
  tags:
    - es

- hosts: tag_ServerType_nfs
  become: yes
  vars_files:
    - ./group_vars/nfs.yml
  tasks:
    - include: ./nfs.yml
  handlers:
    - include: ./handlers/common/restart_iptables.yml
  tags:
    - nfs

- hosts: tag_ServerType_ap
  become: yes
  vars_files:
    - ./group_vars/ap.yml
  tasks:
    - include: ./ap.yml
  handlers:
    - include: ./handlers/common/restart_iptables.yml
  tags:
    - ap

- hosts: tag_ServerType_web
  become: yes
  vars_files:
    - ./group_vars/web.yml
  tasks:
    - include: ./web.yml
  handlers:
    - include: ./handlers/common/restart_iptables.yml
    - include: ./handlers/web/reload_nginx.yml
  tags:
    - web

- hosts: tag_ServerType_bastion
  become: yes
  vars_files:
    - ./group_vars/bastion.yml
  tasks:
    - include: ./tasks/bastion/init_servicemanager.yml
  tags:
    - bastion_post
